name: DungeonChestLoot
version: '${project.version}'
main: best.anarchycraft.dungeonchestloot.Dungeonchestloot
api-version: 1.18
authors: [ ViolationMad ]
description: Randomize and refill dungeon chest loot

commands:
  roll:

  DCL:
    description: Plugins main command. Access the plugins commands via arguments. Type "/dcl help" for syntax.





permissions:
  best:
    anarchycraft:
      dungeonchestloot:
        chests:
          default: OP
          desciption: Needed permission (OP) to add/remove dungeon chest locations