loottable:
  enchants:
    number: 4
    item:
      - FIRE_CHARGE
      - GLOWSTONE_DUST
      - FEATHER
      - TRIPWIRE_HOOK
    displayname:
      - Dragon Essence
      - Stardust
      - Feather of Knowledge
      - Legendary Key
    ncolor:
      - GOLD
      - YELLOW
      - AQUA
      - LIGHT_PURPLE
    lore:
      - Flame I
      - Infinity I
      - Knockback I
      - Fortune I
    lcolor:
      - GRAY
      - GRAY
      - GRAY
      - GRAY
    lore2:
      - 0
      - 0
      - A feather taken from Ra
      - Opens Legendary Chest
    lcolor2:
      - 0
      - 0
      - DARK_AQUA
      - LIGHT_PURPLE
    enchant:
      - flame
      - infinity
      - knockback
      - fortune
    lvl:
      - 1
      - 1
      - 1
      - 1

  serpent:
    lvl1:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
        - NETHERITE_HELMET
        - TRIPWIRE_HOOK
        - NETHER_STAR
        - FEATHER
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
        - 0.1
        - 1
        - 2
        - 5
    lvl2:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
        - EMERALD_ORE
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
        - 64
    lvl3:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl4:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl5:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
  glacial:
    lvl1:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl2:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl3:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl4:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl5:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
  inferno:
    lvl1:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl2:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl3:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl4:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl5:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
  twilight:
    lvl1:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl2:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl3:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl4:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1
    lvl5:
      item:
        - GOLD_BLOCK
        - EMERALD_BLOCK
        - DIAMOND_BLOCK
        - FIRE_CHARGE
        - GLOWSTONE_DUST
        - DRAGON_EGG
        - NETHERITE_SWORD
      amount:
        - 20
        - 15
        - 10
        - 5
        - 5
        - 2
        - 1

chests:
  serpent:
    lvl1:
      numall: 16
      numallw: 5
      location1:
        - 10
        - -60
        - -7
      location2:
        - 10
        - -60
        - -9
      location3:
        - 10
        - -60
        - -11
      location4:
        - 10
        - -60
        - -13
      location5:
        - 12
        - -60
        - -7
      location6:
        - 12
        - -60
        - -9
      location7:
        - 12
        - -60
        - -11
      location8:
        - 12
        - -60
        - -13
      location9:
        - 14
        - -60
        - -7
      location10:
        - 14
        - -60
        - -9
      location11:
        - 14
        - -60
        - -11
      location12:
        - 14
        - -60
        - -13
      location13:
        - 16
        - -60
        - -7
      location14:
        - 16
        - -60
        - -9
      location15:
        - 16
        - -60
        - -11
      location16:
        - 16
        - -60
        - -13
    lvl2:
      numall: 16
      numallw: 5
      location1:
        - 10
        - -57
        - -7
      location2:
        - 10
        - -57
        - -9
      location3:
        - 10
        - -57
        - -11
      location4:
        - 10
        - -57
        - -13
      location5:
        - 12
        - -57
        - -7
      location6:
        - 12
        - -57
        - -9
      location7:
        - 12
        - -57
        - -11
      location8:
        - 12
        - -57
        - -13
      location9:
        - 14
        - -57
        - -7
      location10:
        - 14
        - -57
        - -9
      location11:
        - 14
        - -57
        - -11
      location12:
        - 14
        - -57
        - -13
      location13:
        - 16
        - -57
        - -7
      location14:
        - 16
        - -57
        - -9
      location15:
        - 16
        - -57
        - -11
      location16:
        - 16
        - -57
        - -13
    lvl3:
      numall: 0
      numallw: 5
    lvl4:
      numall: 0
      numallw: 5
    lvl5:
      numall: 0
      numallw: 5
  glacial:
    lvl1:
      numall: 16
      numallw: 5
      location1:
        - 2
        - -60
        - -13
      location2:
        - 4
        - -60
        - -13
      location3:
        - 6
        - -60
        - -13
      location4:
        - 8
        - -60
        - -13
      location5:
        - 2
        - -60
        - -11
      location6:
        - 4
        - -60
        - -11
      location7:
        - 6
        - -60
        - -11
      location8:
        - 8
        - -60
        - -11
      location9:
        - 2
        - -60
        - -9
      location10:
        - 4
        - -60
        - -9
      location11:
        - 6
        - -60
        - -9
      location12:
        - 8
        - -60
        - -9
      location13:
        - 2
        - -60
        - -7
      location14:
        - 4
        - -60
        - -7
      location15:
        - 6
        - -60
        - -7
      location16:
        - 8
        - -60
        - -7
    lvl2:
      numall: 16
      numallw: 5
      location1:
        - 2
        - -57
        - -13
      location2:
        - 4
        - -57
        - -13
      location3:
        - 6
        - -57
        - -13
      location4:
        - 8
        - -57
        - -13
      location5:
        - 2
        - -57
        - -11
      location6:
        - 4
        - -57
        - -11
      location7:
        - 6
        - -57
        - -11
      location8:
        - 8
        - -57
        - -11
      location9:
        - 2
        - -57
        - -9
      location10:
        - 4
        - -57
        - -9
      location11:
        - 6
        - -57
        - -9
      location12:
        - 8
        - -57
        - -9
      location13:
        - 2
        - -57
        - -7
      location14:
        - 4
        - -57
        - -7
      location15:
        - 6
        - -57
        - -7
      location16:
        - 8
        - -57
        - -7
    lvl3:
      numall: 0
      numallw: 5
    lvl4:
      numall: 0
      numallw: 5
    lvl5:
      numall: 0
      numallw: 5
  inferno:
    lvl1:
      numall: 16
      numallw: 5
      location1:
        - -6
        - -60
        - -13
      location2:
        - -4
        - -60
        - -13
      location3:
        - -2
        - -60
        - -13
      location4:
        - 0
        - -60
        - -13
      location5:
        - -6
        - -60
        - -11
      location6:
        - -4
        - -60
        - -11
      location7:
        - -2
        - -60
        - -11
      location8:
        - 0
        - -60
        - -11
      location9:
        - -6
        - -60
        - -9
      location10:
        - -4
        - -60
        - -9
      location11:
        - -2
        - -60
        - -9
      location12:
        - 0
        - -60
        - -9
      location13:
        - -6
        - -60
        - -7
      location14:
        - -4
        - -60
        - -7
      location15:
        - -2
        - -60
        - -7
      location16:
        - 0
        - -60
        - -7
    lvl2:
      numall: 16
      numallw: 5
      location1:
        - -6
        - -57
        - -13
      location2:
        - -4
        - -57
        - -13
      location3:
        - -2
        - -57
        - -13
      location4:
        - 0
        - -57
        - -13
      location5:
        - -6
        - -57
        - -11
      location6:
        - -4
        - -57
        - -11
      location7:
        - -2
        - -57
        - -11
      location8:
        - 0
        - -57
        - -11
      location9:
        - -6
        - -57
        - -9
      location10:
        - -4
        - -57
        - -9
      location11:
        - -2
        - -57
        - -9
      location12:
        - 0
        - -57
        - -9
      location13:
        - -6
        - -57
        - -7
      location14:
        - -4
        - -57
        - -7
      location15:
        - -2
        - -57
        - -7
      location16:
        - 0
        - -57
        - -7
    lvl3:
      numall: 0
      numallw: 5
    lvl4:
      numall: 0
      numallw: 5
    lvl5:
      numall: 0
      numallw: 5
  twilight:
    lvl1:
      numall: 16
      numallw: 5
      location1:
        - -14
        - -60
        - -13
      location2:
        - -12
        - -60
        - -13
      location3:
        - -10
        - -60
        - -13
      location4:
        - -8
        - -60
        - -13
      location5:
        - -14
        - -60
        - -11
      location6:
        - -12
        - -60
        - -11
      location7:
        - -10
        - -60
        - -11
      location8:
        - -8
        - -60
        - -11
      location9:
        - -14
        - -60
        - -9
      location10:
        - -12
        - -60
        - -9
      location11:
        - -10
        - -60
        - -9
      location12:
        - -8
        - -60
        - -9
      location13:
        - -14
        - -60
        - -7
      location14:
        - -12
        - -60
        - -7
      location15:
        - -10
        - -60
        - -7
      location16:
        - -8
        - -60
        - -7
    lvl2:
      numall: 16
      numallw: 5
      location1:
        - -14
        - -57
        - -13
      location2:
        - -12
        - -57
        - -13
      location3:
        - -10
        - -57
        - -13
      location4:
        - -8
        - -57
        - -13
      location5:
        - -14
        - -57
        - -11
      location6:
        - -12
        - -57
        - -11
      location7:
        - -10
        - -57
        - -11
      location8:
        - -8
        - -57
        - -11
      location9:
        - -14
        - -57
        - -9
      location10:
        - -12
        - -57
        - -9
      location11:
        - -10
        - -57
        - -9
      location12:
        - -8
        - -57
        - -9
      location13:
        - -14
        - -57
        - -7
      location14:
        - -12
        - -57
        - -7
      location15:
        - -10
        - -57
        - -7
      location16:
        - -8
        - -57
        - -7
    lvl3:
      numall: 0
      numallw: 5
    lvl4:
      numall: 0
      numallw: 5
    lvl5:
      numall: 0
      numallw: 5
